**

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!.npmrc
!tsconfig.base.json
!tsconfig.json

!apps
!apps/admin-web
!apps/admin-web/**
apps/admin-web/.next
apps/admin-web/node_modules
apps/admin-web/*.log
apps/admin-web/tsconfig.tsbuildinfo
apps/admin-web/.env
apps/admin-web/.env.*

!packages
!packages/**

!patches
!patches/**
