ALTER TYPE "InspectionItemInputType" ADD VALUE IF NOT EXISTS 'MULTI_SELECT';
ALTER TYPE "InspectionItemInputType" ADD VALUE IF NOT EXISTS 'IMAGE';
ALTER TYPE "InspectionItemInputType" ADD VALUE IF NOT EXISTS 'GPS';
ALTER TYPE "InspectionItemInputType" ADD VALUE IF NOT EXISTS 'READING';
