**

!package.json
!pnpm-lock.yaml
!pnpm-workspace.yaml
!.npmrc
!tsconfig.base.json
!tsconfig.json

!apps
!apps/api
!apps/api/package.json
!apps/api/tsconfig.json
!apps/api/tsconfig.build.json
!apps/api/src
!apps/api/src/**

!packages
!packages/**

!prisma
!prisma/schema.prisma
!prisma/migrations
!prisma/migrations/**

!patches
!patches/**
